### PR TITLE
fix: fatal unsafe repository

### PR DESCRIPTION
**Pull request by dotennin**
Git security vulnerability announced
https://github.blog/2022-04-12-git-security-vulnerability-announced/

Related issue: https://github.com/actions/checkout/issues/760

### CODE REVIEW

**Review by kevinvella1 — APPROVED** [review]

**Comment by kevinvella1** [comment]
Can we merge this please? We are also experiencing this issue.

@[dotennin](https://github.com/dotennin)

**Comment by dotennin** [comment]
> Can we merge this please? We are also experiencing this issue.
> 
> @[dotennin](https://github.com/dotennin)

Yeah, it need author's approval
@himadrisingh @Borda  can you please approve this PR.

**Comment by himadrisingh** [comment]
This should be fixed by https://github.com/gorillio/github-action-cherry-pick/pull/7, no?

**Comment by himadrisingh** [comment]
Should have checked your PR

**Review by himadrisingh — APPROVED** [review]

**Comment by dotennin** [comment]
> This should be fixed by #7, no?

Oh didn't know that . will close 😅

**Pull request closed without merging**
